  instanceName: Ready CI

  pipelines:
  - name: readyci
    parameters:
      gitPath: git@github.com:dotb/ready_ci.git
      gitBranch: master
      deploySrcPath: target/readyci-0.1.jar
      deployDstPath: /tmp/readyci.jar

    tasks:
    - task: maven_install # Run maven install

    - task: deploy_copy # Copy the built binary to a deployment destination

    - task: build_path_clean # Finish up by cleaning the build folder

  - name: build-an-ios-app
    parameters:
      gitPath: <git url>
      gitBranch: master
      projectPath: ios app
      workspace: <workspace name>
      scheme: <target name>
      configuration: Release
      infoPlistPath: <path to Info.plist>
      hockappToken: <token>
      hockeyappReleaseTags: <tags for release users or groups>
      hockeyappReleaseNotes: New app build available
      iTunesUsername: <itunes upload username>
      iTunesPassword: <itunes upload password>
      gitCommitMessage: Bumped the build number using Real CI
      gitCommitFileList:
      - <list of updated files to commit back to the repo>
      iosProfiles:
      - <file 1>.mobileprovision
      - <file 2>.mobileprovision

    tasks:
    - task: ios_pod_install # Pod install

    - task: ios_provisioning_profile_read # Read the provisioning profile and add parameters to the build environment

    - task: ios_export_options_create # Create a exportOptions.plist file

    - task: ios_install_provisioning_profile # Install the provisioning profile in XCode

    - task: ios_increment_build_number # Increment the build number

    - task: ios_archive # Generate an iOS archive

    - task: ios_export # Sign and export the iOS app

    - task: ios_upload_itunes_connect # Upload the binary to iTunes Connect

    - task: build_path_clean # Finish up by cleaning the build folder