  instanceName: Ready CI

  pipelines:
  - name: readyci
    parameters:
      gitPath: git@github.com:dotb/ready_ci.git
      gitBranch: master
      deploySrcPath: target/readyci-0.1.jar
      deployDstPath: /tmp/readyci.jar

    tasks:
    - description: Run maven install
      type: maven_install

    - description: Copy the built binary to a deployment destination
      type: deploy_copy

    - description: Finish up by cleaning the build folder
      type: build_path_clean

  - name: build-an-ios-app
    parameters:
      gitPath: <git url>
      gitBranch: master
      projectPath: ios app
      workspace: <workspace name>
      scheme: <target name>
      configuration: Release
      infoPlistPath: <path to Info.plist>
      hockappToken: <token>
      hockeyappReleaseTags: <tags for release users or groups>
      hockeyappReleaseNotes: New app build available
      iTunesUsername: <itunes upload username>
      iTunesPassword: <itunes upload password>
      gitCommitMessage: Bumped the build number using Real CI
      gitCommitFileList:
      - <list of updated files to commit back to the repo>
      iosProfiles:
      - <file 1>.mobileprovision
      - <file 2>.mobileprovision

    tasks:
    - description: Pod install
      type: ios_pod_install

    - description: Read the provisioning profile and add parameters to the build environment
      type: ios_provisioning_profile_read

    - description: Create a exportOptions.plist file
      type: ios_export_options_create

    - description: Install the provisioning profile in XCode
      type: ios_install_provisioning_profile

    - description: Increment the build number
      type: ios_increment_build_number

    - description: Generate an iOS archive
      type: ios_archive

    - description: Sign and export the iOS app
      type: ios_export

    - description: Upload the binary to iTunes Connect
      type: ios_upload_itunes_connect

    - description: Finish up by cleaning the build folder
      type: build_path_clean